#!/usr/bin/python
import socket, datetime, time, pytz

sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)

met = pytz.timezone("Europe/Berlin")
def current_time():
    now = datetime.datetime.utcnow()
    now = now.replace(tzinfo=pytz.utc)
    now = now.astimezone(met)
    now = now.replace(tzinfo=None)
    return now

def send_clock():
    now = current_time()

    since_midnight = (
        now - 
        now.replace(hour=0, minute=0, second=0, microsecond=0)
    ).seconds

    sock.sendto('root/clock/time:%f' % since_midnight, ('127.0.0.1', 4444))
    sock.sendto('root/clock/weekday:%d' % now.isoweekday(), ('127.0.0.1', 4444))
    sock.sendto('root/clock/monthday:%d' % now.day, ('127.0.0.1', 4444))

while 1:
    send_clock()
    time.sleep(5)

