#!/usr/bin/python
import sys
import time
import requests
import traceback
from hosted import DEVICE

def check_and_update_power():
    r = requests.get("http://status.club.entropia.de/status.json", headers={
        'User-Agent': 'club info-beamer power toggle'
    })
    r.raise_for_status()
    club_open = r.json()['club_offen']
    print >>sys.stderr, "club status is %s" % (('closed', 'open')[club_open])
    if club_open:
        DEVICE.turn_screen_on()
    else:
        DEVICE.turn_screen_off()
    
def main():
    print >>sys.stderr, "power running"
    while 1:
        try:
            check_and_update_power()
            time.sleep(5)
        except:
            traceback.print_exc()
            time.sleep(60)

if __name__ == "__main__":
    main()
