#!/usr/bin/python
import httplib, json, socket, time, pprint, re
sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)

time.sleep(5)

socket.setdefaulttimeout(10.0)

def strip_html(text):
    return re.sub('<[^<]+?>', '', text)

def get_termine():
    conn = httplib.HTTPSConnection("entropia.de")
    conn.request("GET","/api.php?format=json&action=parse&page=Vorlage:Termine")
    res = conn.getresponse()
    data = json.loads(res.read())
    # pprint.pprint(data)
    html = data['parse']['text']['*'].replace("\n", "")
    row_re = re.compile("<tr>.*?<td>(.*?)</td>.*?<td>(.*?)</td>.*?<td>(.*?)</td>.*?<td>(.*?)</td>.*?</tr>")
    termine = []
    for row in row_re.finditer(html, re.I):
        date, time, place, desc = [strip_html(col).strip() for col in row.groups()]
        termine.append(dict(
            date = date,
            time = time,
            place = place,
            desc = desc
        ))
    return termine

while 1:
    termine = json.dumps(get_termine(), ensure_ascii=False).encode("utf8")
    print(termine)
    with file("termine.json", "wb") as f:
        f.write(termine)
    time.sleep(3600)
