#!/usr/bin/python
import socket, datetime, time, pytz

sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
ber = pytz.timezone("Europe/Berlin")

def send_clock():
    now = datetime.datetime.now(ber)

    sock.sendto('root/clock/hours:%f' % now.hour, ('127.0.0.1', 4444))
    sock.sendto('root/clock/minutes:%f' % now.minute, ('127.0.0.1', 4444))
    sock.sendto('root/clock/seconds:%f' % now.second, ('127.0.0.1', 4444))
    sock.sendto('root/clock/iso_date:%d' % now.date.isoformat(), ('127.0.0.1', 4444))

while 1:
    send_clock()
    time.sleep(5)
