#!/usr/bin/python
import httplib, json, socket, time, traceback
sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)

while 1:
    try:
        conn = httplib.HTTPConnection("dampfmaschine.club.entropia.de", 7535)
        conn.request("GET", "/api/backlight")
        res = conn.getresponse()
        data = res.read()
        one = 1.0 / 255 * 0.5
        r, g, b = one * int(data[0:2], 16), one * int(data[2:4], 16), one * int(data[4:6], 16)
        color = json.dumps(dict(
            r = r,
            g = g,
            b = b,
        ))

        sock.sendto('root/bgcolor:%s' % color, ('127.0.0.1', 4444))
        time.sleep(1)
    except Exception, err:
        traceback.print_exc()
        time.sleep(30)
